CREATE TABLE feature_materialization_run (
    run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    command_hash text NOT NULL,
    status text NOT NULL,
    version bigint NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE feature_materialization_task (
    run_id bigint NOT NULL,
    task_key text NOT NULL,
    symbol text NOT NULL,
    feature_id text NOT NULL,
    timeframe text NOT NULL,
    status text NOT NULL,
    version bigint NOT NULL,
    claim_token text,
    claimed_at timestamptz,
    artifact_id text,
    artifact_hash text,
    last_error text,
    PRIMARY KEY (run_id, task_key),
    FOREIGN KEY (run_id) REFERENCES feature_materialization_run(run_id)
);

CREATE TABLE feature_materialization_attempt (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL,
    task_key text NOT NULL,
    attempt_number bigint NOT NULL,
    claim_token text NOT NULL,
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    status text NOT NULL,
    error_message text,
    UNIQUE (run_id, task_key, attempt_number),
    FOREIGN KEY (run_id, task_key)
        REFERENCES feature_materialization_task(run_id, task_key)
);

CREATE TABLE feature_materialization_receipt (
    run_id bigint PRIMARY KEY,
    receipt_id text NOT NULL UNIQUE,
    receipt_hash text NOT NULL,
    receipt_json text NOT NULL,
    created_at timestamptz NOT NULL,
    FOREIGN KEY (run_id) REFERENCES feature_materialization_run(run_id)
);

CREATE TABLE feature_materialization_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL,
    task_key text,
    event_type text NOT NULL,
    event_time timestamptz NOT NULL,
    payload_json text NOT NULL,
    FOREIGN KEY (run_id) REFERENCES feature_materialization_run(run_id)
);
