CREATE TABLE controlled_operation_run (
    run_id text PRIMARY KEY,
    idempotency_key text NOT NULL UNIQUE,
    command_hash text NOT NULL CHECK (
        command_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    command_json text NOT NULL CHECK (command_json IS JSON OBJECT),
    decision_date date NOT NULL,
    status text NOT NULL CHECK (
        status IN (
            'CREATED',
            'WAITING_FOR_STATIC_INPUTS',
            'STATIC_READY',
            'WAITING_FOR_DECISION_WINDOW',
            'DECISION_WINDOW_RUNNING',
            'DATA_BLOCKED',
            'DEADLINE_MISSED',
            'OUTCOME_PENDING',
            'SETTLED',
            'FAILED'
        )
    ),
    current_stage text CHECK (
        current_stage IS NULL OR current_stage IN (
            'CALENDAR_UNIVERSE_FREEZE',
            'DAILY_SOURCE_FREEZE',
            'DAILY_DATASET',
            'STATIC_FEATURES',
            'OPERATIONAL_RESEARCH',
            'CANDIDATE_SET',
            'CANDIDATE_MINUTE_ACQUISITION',
            'INTRADAY_DATASET',
            'INTRADAY_FEATURE_OVERLAY',
            'SIGNAL',
            'PATH_FORECAST',
            'ENTRY_ASSESSMENT',
            'OPERATION_PACKAGE',
            'OUTCOME_SETTLEMENT'
        )
    ),
    version bigint NOT NULL CHECK (version >= 1),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    settled_at timestamptz,
    CHECK ((status = 'SETTLED') = (settled_at IS NOT NULL))
);

CREATE TABLE controlled_operation_stage (
    run_id text NOT NULL,
    stage_name text NOT NULL CHECK (
        stage_name IN (
            'CALENDAR_UNIVERSE_FREEZE',
            'DAILY_SOURCE_FREEZE',
            'DAILY_DATASET',
            'STATIC_FEATURES',
            'OPERATIONAL_RESEARCH',
            'CANDIDATE_SET',
            'CANDIDATE_MINUTE_ACQUISITION',
            'INTRADAY_DATASET',
            'INTRADAY_FEATURE_OVERLAY',
            'SIGNAL',
            'PATH_FORECAST',
            'ENTRY_ASSESSMENT',
            'OPERATION_PACKAGE',
            'OUTCOME_SETTLEMENT'
        )
    ),
    status text NOT NULL CHECK (
        status IN ('PENDING', 'IN_PROGRESS', 'FAILED', 'COMPLETED')
    ),
    version bigint NOT NULL CHECK (version >= 1),
    claim_id text,
    claim_epoch bigint NOT NULL DEFAULT 0 CHECK (claim_epoch >= 0),
    lease_acquired_at timestamptz,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    receipt_id text UNIQUE,
    receipt_hash text CHECK (
        receipt_hash IS NULL OR receipt_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    last_error text,
    PRIMARY KEY (run_id, stage_name),
    FOREIGN KEY (run_id)
        REFERENCES controlled_operation_run(run_id) ON DELETE RESTRICT,
    CHECK ((receipt_id IS NULL) = (receipt_hash IS NULL)),
    CHECK (
        (
            status = 'IN_PROGRESS'
            AND claim_id IS NOT NULL
            AND claim_epoch >= 1
            AND lease_acquired_at IS NOT NULL
            AND lease_expires_at IS NOT NULL
            AND heartbeat_at IS NOT NULL
            AND receipt_id IS NULL
        ) OR (
            status != 'IN_PROGRESS'
            AND claim_id IS NULL
            AND lease_acquired_at IS NULL
            AND lease_expires_at IS NULL
            AND heartbeat_at IS NULL
        )
    ),
    CHECK (
        (status = 'COMPLETED' AND receipt_id IS NOT NULL)
        OR (status != 'COMPLETED' AND receipt_id IS NULL)
    )
);

CREATE TABLE controlled_operation_attempt (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    stage_name text NOT NULL,
    attempt_number bigint NOT NULL CHECK (attempt_number >= 1),
    claim_id text NOT NULL,
    claim_epoch bigint NOT NULL CHECK (claim_epoch >= 1),
    stage_version bigint NOT NULL CHECK (stage_version >= 2),
    started_at timestamptz NOT NULL,
    lease_expires_at timestamptz NOT NULL,
    heartbeat_at timestamptz NOT NULL,
    completed_at timestamptz,
    status text NOT NULL CHECK (
        status IN ('STARTED', 'COMPLETED', 'FAILED', 'LEASE_EXPIRED')
    ),
    error_message text,
    UNIQUE (run_id, stage_name, attempt_number),
    UNIQUE (run_id, stage_name, claim_epoch),
    FOREIGN KEY (run_id, stage_name)
        REFERENCES controlled_operation_stage(run_id, stage_name)
        ON DELETE RESTRICT,
    CHECK (
        (status = 'STARTED' AND completed_at IS NULL)
        OR (status != 'STARTED' AND completed_at IS NOT NULL)
    )
);

CREATE TABLE controlled_operation_receipt (
    receipt_id text PRIMARY KEY,
    receipt_hash text NOT NULL CHECK (
        receipt_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    run_id text NOT NULL,
    stage_name text NOT NULL,
    attempt_number bigint NOT NULL CHECK (attempt_number >= 1),
    receipt_json text NOT NULL CHECK (receipt_json IS JSON OBJECT),
    created_at timestamptz NOT NULL,
    UNIQUE (run_id, stage_name),
    UNIQUE (run_id, stage_name, receipt_hash),
    UNIQUE (receipt_id, run_id, stage_name),
    FOREIGN KEY (run_id, stage_name, attempt_number)
        REFERENCES controlled_operation_attempt(run_id, stage_name, attempt_number)
        ON DELETE RESTRICT
);

CREATE INDEX controlled_operation_receipt_attempt_idx
ON controlled_operation_receipt(run_id, stage_name, attempt_number);

CREATE TABLE controlled_operation_child_run (
    run_id text NOT NULL,
    stage_name text NOT NULL,
    reference_kind text NOT NULL CHECK (
        reference_kind IN (
            'DAILY_ACQUISITION_RUN',
            'STATIC_FEATURE_RUN',
            'MINUTE_ACQUISITION_BATCH',
            'INTRADAY_FEATURE_RUN',
            'CANONICAL_LIFECYCLE_RUN',
            'OUTCOME_RUN'
        )
    ),
    child_run_id text NOT NULL,
    child_receipt_hash text NOT NULL CHECK (
        child_receipt_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    receipt_id text NOT NULL,
    PRIMARY KEY (run_id, reference_kind, child_run_id),
    FOREIGN KEY (receipt_id, run_id, stage_name)
        REFERENCES controlled_operation_receipt(receipt_id, run_id, stage_name)
        ON DELETE RESTRICT
);

CREATE INDEX controlled_operation_child_receipt_idx
ON controlled_operation_child_run(receipt_id, run_id, stage_name);

CREATE TABLE controlled_operation_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    stage_name text,
    event_type text NOT NULL CHECK (
        event_type IN (
            'RUN_CREATED',
            'RUN_RESUMED',
            'RUN_STATUS_CHANGED',
            'STAGE_CLAIMED',
            'STAGE_HEARTBEAT',
            'STAGE_COMPLETED',
            'STAGE_FAILED',
            'LEASE_EXPIRED',
            'RECEIPT_RECORDED'
        )
    ),
    event_time timestamptz NOT NULL,
    payload_json text NOT NULL CHECK (payload_json IS JSON OBJECT),
    FOREIGN KEY (run_id)
        REFERENCES controlled_operation_run(run_id) ON DELETE RESTRICT,
    FOREIGN KEY (run_id, stage_name)
        REFERENCES controlled_operation_stage(run_id, stage_name)
        ON DELETE RESTRICT
);

CREATE INDEX controlled_operation_run_status_date_idx
ON controlled_operation_run(status, decision_date, run_id);
CREATE INDEX controlled_operation_stage_claimable_idx
ON controlled_operation_stage(run_id, status, stage_name);
CREATE INDEX controlled_operation_stage_lease_idx
ON controlled_operation_stage(run_id, status, lease_expires_at);
CREATE INDEX controlled_operation_attempt_history_idx
ON controlled_operation_attempt(run_id, stage_name, attempt_number);
CREATE INDEX controlled_operation_event_history_idx
ON controlled_operation_event(run_id, event_id);
CREATE INDEX controlled_operation_event_stage_idx
ON controlled_operation_event(run_id, stage_name);
CREATE INDEX controlled_operation_child_run_lookup_idx
ON controlled_operation_child_run(reference_kind, child_run_id, run_id);

CREATE TRIGGER controlled_operation_events_no_update
BEFORE UPDATE ON controlled_operation_event
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER controlled_operation_events_no_delete
BEFORE DELETE ON controlled_operation_event
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER controlled_operation_receipts_no_update
BEFORE UPDATE ON controlled_operation_receipt
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER controlled_operation_receipts_no_delete
BEFORE DELETE ON controlled_operation_receipt
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER controlled_operation_child_runs_no_update
BEFORE UPDATE ON controlled_operation_child_run
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER controlled_operation_child_runs_no_delete
BEFORE DELETE ON controlled_operation_child_run
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

CREATE FUNCTION guard_controlled_attempt_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Controlled operation attempts are append-only';
    END IF;
    IF OLD.status != 'STARTED' THEN
        RAISE EXCEPTION 'Settled Controlled operation attempts are immutable';
    END IF;
    IF NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.stage_name IS DISTINCT FROM OLD.stage_name
       OR NEW.attempt_number IS DISTINCT FROM OLD.attempt_number
       OR NEW.claim_id IS DISTINCT FROM OLD.claim_id
       OR NEW.claim_epoch IS DISTINCT FROM OLD.claim_epoch
       OR NEW.stage_version IS DISTINCT FROM OLD.stage_version
       OR NEW.started_at IS DISTINCT FROM OLD.started_at THEN
        RAISE EXCEPTION 'Controlled operation attempt identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER controlled_operation_attempts_no_delete
BEFORE DELETE ON controlled_operation_attempt
FOR EACH ROW EXECUTE FUNCTION guard_controlled_attempt_mutation();
CREATE TRIGGER controlled_operation_attempt_identity_guard
BEFORE UPDATE ON controlled_operation_attempt
FOR EACH ROW EXECUTE FUNCTION guard_controlled_attempt_mutation();

CREATE FUNCTION guard_controlled_stage_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Controlled operation stages cannot be deleted';
    END IF;
    IF OLD.status = 'COMPLETED' THEN
        RAISE EXCEPTION 'Completed Controlled operation stage is immutable';
    END IF;
    IF OLD.status = 'IN_PROGRESS' AND NEW.status = 'IN_PROGRESS' AND (
        NEW.claim_id IS DISTINCT FROM OLD.claim_id
        OR NEW.claim_epoch IS DISTINCT FROM OLD.claim_epoch
    ) THEN
        RAISE EXCEPTION 'Active Controlled operation claim cannot be overwritten';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER controlled_operation_stages_no_delete
BEFORE DELETE ON controlled_operation_stage
FOR EACH ROW EXECUTE FUNCTION guard_controlled_stage_mutation();
CREATE TRIGGER controlled_operation_completed_stage_immutable
BEFORE UPDATE ON controlled_operation_stage
FOR EACH ROW EXECUTE FUNCTION guard_controlled_stage_mutation();

CREATE FUNCTION guard_controlled_run_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Controlled operation runs cannot be deleted';
    END IF;
    IF NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.command_hash IS DISTINCT FROM OLD.command_hash
       OR NEW.command_json IS DISTINCT FROM OLD.command_json
       OR NEW.decision_date IS DISTINCT FROM OLD.decision_date
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'Controlled operation command identity is immutable';
    END IF;
    IF (OLD.status = 'OUTCOME_PENDING'
        AND NEW.status NOT IN ('OUTCOME_PENDING', 'SETTLED'))
       OR (OLD.status = 'SETTLED' AND NEW.status != 'SETTLED') THEN
        RAISE EXCEPTION 'Controlled operation terminal status cannot regress';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER controlled_operation_runs_no_delete
BEFORE DELETE ON controlled_operation_run
FOR EACH ROW EXECUTE FUNCTION guard_controlled_run_mutation();
CREATE TRIGGER controlled_operation_run_identity_immutable
BEFORE UPDATE ON controlled_operation_run
FOR EACH ROW EXECUTE FUNCTION guard_controlled_run_mutation();
