ALTER TABLE runtime_database_bindings
DROP CONSTRAINT runtime_database_bindings_scope_type_check;

ALTER TABLE runtime_database_bindings
ADD CONSTRAINT runtime_database_bindings_scope_type_check
CHECK (
    scope_type IN (
        'CANONICAL_LIFECYCLE',
        'CONTROLLED_OPERATION',
        'DAILY_LOOP',
        'FREE_DATA_OPERATION',
        'CONTINUOUS_RESEARCH'
    )
);

CREATE TABLE continuous_research_run (
    run_id text PRIMARY KEY,
    idempotency_key text NOT NULL UNIQUE,
    command_hash text NOT NULL CHECK (
        command_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    command_json text NOT NULL CHECK (command_json IS JSON OBJECT),
    trading_date date NOT NULL,
    request_scope_hash text NOT NULL CHECK (
        request_scope_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    policy_id text NOT NULL,
    policy_hash text NOT NULL CHECK (
        policy_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    provider_configuration_id text NOT NULL,
    provider_configuration_hash text NOT NULL CHECK (
        provider_configuration_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    research_configuration_id text NOT NULL,
    research_configuration_hash text NOT NULL CHECK (
        research_configuration_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    status text NOT NULL CHECK (
        status IN (
            'CREATED',
            'PREPARING',
            'MONITORING',
            'WAITING_FOR_NEW_DATA',
            'RECOMPUTING',
            'DECISION_WINDOW_OPEN',
            'MARKET_CLOSED',
            'ARCHIVED',
            'DATA_BLOCKED',
            'DEGRADED',
            'RETRYING',
            'FAILED',
            'CANCELLED'
        )
    ),
    current_tick_sequence bigint NOT NULL DEFAULT 0 CHECK (
        current_tick_sequence >= 0
    ),
    version bigint NOT NULL CHECK (version >= 1),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    closed_at timestamptz,
    archived_at timestamptz,
    CHECK ((status = 'ARCHIVED') = (archived_at IS NOT NULL)),
    CHECK (archived_at IS NULL OR closed_at IS NOT NULL)
);

CREATE TABLE continuous_runtime_tick (
    run_id text NOT NULL,
    tick_id text NOT NULL,
    idempotency_key text NOT NULL UNIQUE,
    tick_hash text NOT NULL CHECK (
        tick_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    tick_json text NOT NULL CHECK (tick_json IS JSON OBJECT),
    tick_sequence bigint NOT NULL CHECK (tick_sequence >= 1),
    observed_at timestamptz NOT NULL,
    session_phase text NOT NULL CHECK (
        session_phase IN (
            'PRE_MARKET',
            'MORNING_SESSION',
            'MIDDAY_RECESS',
            'AFTERNOON_SESSION',
            'DECISION_WINDOW',
            'MARKET_CLOSED'
        )
    ),
    status text NOT NULL CHECK (
        status IN (
            'PENDING',
            'IN_PROGRESS',
            'COMPLETED',
            'FAILED',
            'DATA_BLOCKED'
        )
    ),
    version bigint NOT NULL CHECK (version >= 1),
    claim_id text,
    fencing_token bigint NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
    lease_acquired_at timestamptz,
    lease_expires_at timestamptz,
    heartbeat_at timestamptz,
    provider_attempt_id bigint,
    evidence_commit_id text,
    change_decision_id text,
    receipt_id text UNIQUE,
    receipt_hash text CHECK (
        receipt_hash IS NULL OR receipt_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    receipt_json text CHECK (
        receipt_json IS NULL OR receipt_json IS JSON OBJECT
    ),
    last_error text,
    retry_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    completed_at timestamptz,
    PRIMARY KEY (run_id, tick_id),
    UNIQUE (run_id, tick_sequence),
    FOREIGN KEY (run_id)
        REFERENCES continuous_research_run(run_id) ON DELETE RESTRICT,
    CHECK ((receipt_id IS NULL) = (receipt_hash IS NULL)),
    CHECK ((receipt_id IS NULL) = (receipt_json IS NULL)),
    CHECK (
        (
            status = 'IN_PROGRESS'
            AND claim_id IS NOT NULL
            AND fencing_token >= 1
            AND lease_acquired_at IS NOT NULL
            AND lease_expires_at IS NOT NULL
            AND heartbeat_at IS NOT NULL
            AND completed_at IS NULL
        ) OR (
            status != 'IN_PROGRESS'
            AND claim_id IS NULL
            AND lease_acquired_at IS NULL
            AND lease_expires_at IS NULL
            AND heartbeat_at IS NULL
        )
    ),
    CHECK (
        (
            status = 'COMPLETED'
            AND receipt_id IS NOT NULL
            AND completed_at IS NOT NULL
        ) OR (
            status != 'COMPLETED'
            AND receipt_id IS NULL
        )
    )
);

CREATE TABLE continuous_provider_attempt (
    attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    tick_id text NOT NULL,
    attempt_number bigint NOT NULL CHECK (attempt_number >= 1),
    claim_id text NOT NULL,
    fencing_token bigint NOT NULL CHECK (fencing_token >= 1),
    tick_version bigint NOT NULL CHECK (tick_version >= 2),
    provider_id text NOT NULL,
    product text NOT NULL,
    request_hash text NOT NULL CHECK (
        request_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    lease_expires_at timestamptz NOT NULL,
    heartbeat_at timestamptz NOT NULL,
    status text NOT NULL CHECK (
        status IN (
            'STARTED',
            'SUCCEEDED',
            'FAILED',
            'TIMED_OUT',
            'INVALID_RESPONSE',
            'RATE_LIMITED',
            'CIRCUIT_OPEN',
            'LEASE_EXPIRED'
        )
    ),
    raw_response_hash text CHECK (
        raw_response_hash IS NULL OR raw_response_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    source_manifest_id text,
    source_manifest_hash text CHECK (
        source_manifest_hash IS NULL OR source_manifest_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    error_code text,
    error_message text,
    reason_codes_json text NOT NULL CHECK (reason_codes_json IS JSON ARRAY),
    retry_at timestamptz,
    provider_revision text,
    attempt_json text NOT NULL CHECK (attempt_json IS JSON OBJECT),
    UNIQUE (run_id, tick_id, attempt_number),
    UNIQUE (run_id, tick_id, fencing_token),
    UNIQUE (attempt_id, run_id, tick_id),
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id)
        ON DELETE RESTRICT,
    CHECK (
        (status = 'STARTED' AND completed_at IS NULL)
        OR (status != 'STARTED' AND completed_at IS NOT NULL)
    ),
    CHECK ((source_manifest_id IS NULL) = (source_manifest_hash IS NULL)),
    CHECK (status != 'SUCCEEDED' OR source_manifest_id IS NOT NULL)
);

CREATE TABLE continuous_evidence_commit (
    evidence_commit_id text PRIMARY KEY,
    commit_hash text NOT NULL CHECK (
        commit_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    run_id text NOT NULL,
    tick_id text NOT NULL,
    attempt_id bigint NOT NULL UNIQUE,
    evidence_scope text NOT NULL,
    trading_date date NOT NULL,
    request_scope_hash text NOT NULL CHECK (
        request_scope_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    source_manifest_id text NOT NULL,
    source_manifest_hash text NOT NULL CHECK (
        source_manifest_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    raw_artifact_id text,
    raw_artifact_hash text CHECK (
        raw_artifact_hash IS NULL OR raw_artifact_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    evidence_artifact_id text NOT NULL,
    evidence_artifact_hash text NOT NULL CHECK (
        evidence_artifact_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    material_identity_hash text NOT NULL CHECK (
        material_identity_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    provider_configuration_id text NOT NULL,
    provider_configuration_hash text NOT NULL CHECK (
        provider_configuration_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    effective_at timestamptz NOT NULL,
    retrieved_at timestamptz NOT NULL,
    available_at timestamptz NOT NULL,
    as_of_time timestamptz NOT NULL,
    quality_status text NOT NULL CHECK (
        quality_status IN ('VALIDATED', 'DEGRADED', 'PIT_INCOMPLETE')
    ),
    evidence_qualification text NOT NULL,
    evidence_json text NOT NULL CHECK (evidence_json IS JSON OBJECT),
    created_at timestamptz NOT NULL,
    UNIQUE (evidence_commit_id, run_id),
    UNIQUE (evidence_commit_id, run_id, tick_id),
    UNIQUE (evidence_commit_id, run_id, evidence_scope),
    FOREIGN KEY (attempt_id, run_id, tick_id)
        REFERENCES continuous_provider_attempt(attempt_id, run_id, tick_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id)
        ON DELETE RESTRICT,
    CHECK ((raw_artifact_id IS NULL) = (raw_artifact_hash IS NULL)),
    CHECK (available_at >= effective_at),
    CHECK (retrieved_at >= effective_at)
);

CREATE TABLE continuous_current_evidence (
    run_id text NOT NULL,
    evidence_scope text NOT NULL,
    evidence_commit_id text NOT NULL,
    evidence_commit_hash text NOT NULL CHECK (
        evidence_commit_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    material_identity_hash text NOT NULL CHECK (
        material_identity_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    version bigint NOT NULL CHECK (version >= 1),
    last_accepted_fencing_token bigint NOT NULL CHECK (
        last_accepted_fencing_token >= 1
    ),
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (run_id, evidence_scope),
    UNIQUE (evidence_commit_id, run_id, evidence_scope),
    FOREIGN KEY (run_id)
        REFERENCES continuous_research_run(run_id) ON DELETE RESTRICT,
    FOREIGN KEY (evidence_commit_id, run_id, evidence_scope)
        REFERENCES continuous_evidence_commit(
            evidence_commit_id, run_id, evidence_scope
        ) ON DELETE RESTRICT
);

CREATE TABLE continuous_change_decision (
    decision_id text PRIMARY KEY,
    decision_hash text NOT NULL CHECK (
        decision_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    run_id text NOT NULL,
    tick_id text NOT NULL,
    provider_attempt_id bigint NOT NULL,
    evidence_commit_id text NOT NULL,
    previous_evidence_commit_id text,
    decision_type text NOT NULL CHECK (
        decision_type IN (
            'INITIAL_EVIDENCE',
            'MATERIAL_CHANGE',
            'NO_MATERIAL_CHANGE',
            'DATA_INSUFFICIENT'
        )
    ),
    previous_material_identity_hash text CHECK (
        previous_material_identity_hash IS NULL
        OR previous_material_identity_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    current_material_identity_hash text NOT NULL CHECK (
        current_material_identity_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    reason_codes_json text NOT NULL CHECK (reason_codes_json IS JSON ARRAY),
    decision_json text NOT NULL CHECK (decision_json IS JSON OBJECT),
    created_at timestamptz NOT NULL,
    UNIQUE (run_id, tick_id),
    UNIQUE (decision_id, run_id, tick_id),
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (provider_attempt_id, run_id, tick_id)
        REFERENCES continuous_provider_attempt(attempt_id, run_id, tick_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (evidence_commit_id, run_id, tick_id)
        REFERENCES continuous_evidence_commit(evidence_commit_id, run_id, tick_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (previous_evidence_commit_id, run_id)
        REFERENCES continuous_evidence_commit(evidence_commit_id, run_id)
        ON DELETE RESTRICT,
    CHECK (
        (previous_evidence_commit_id IS NULL)
        = (previous_material_identity_hash IS NULL)
    ),
    CHECK (
        decision_type != 'INITIAL_EVIDENCE'
        OR previous_evidence_commit_id IS NULL
    )
);

CREATE TABLE continuous_child_run (
    run_id text NOT NULL,
    tick_id text NOT NULL,
    decision_id text NOT NULL,
    child_kind text NOT NULL CHECK (
        child_kind IN (
            'DAILY_DATASET',
            'FEATURE_MATERIALIZATION',
            'CONTROLLED_OPERATION',
            'CANONICAL_LIFECYCLE'
        )
    ),
    reference_disposition text NOT NULL CHECK (
        reference_disposition IN ('CREATED', 'REUSED')
    ),
    child_run_id text NOT NULL,
    child_receipt_id text NOT NULL,
    child_receipt_hash text NOT NULL CHECK (
        child_receipt_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    child_artifact_id text,
    child_artifact_hash text CHECK (
        child_artifact_hash IS NULL OR child_artifact_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    source_manifest_id text NOT NULL,
    source_manifest_hash text NOT NULL CHECK (
        source_manifest_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    aggregate_input_hash text NOT NULL CHECK (
        aggregate_input_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    configuration_set_hash text NOT NULL CHECK (
        configuration_set_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    child_reference_json text NOT NULL CHECK (
        child_reference_json IS JSON OBJECT
    ),
    created_at timestamptz NOT NULL,
    PRIMARY KEY (run_id, tick_id, child_kind, child_run_id),
    UNIQUE (run_id, tick_id, child_kind),
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (decision_id, run_id, tick_id)
        REFERENCES continuous_change_decision(decision_id, run_id, tick_id)
        ON DELETE RESTRICT,
    CHECK ((child_artifact_id IS NULL) = (child_artifact_hash IS NULL))
);

CREATE TABLE continuous_runtime_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    tick_id text,
    event_type text NOT NULL CHECK (
        event_type IN (
            'RUN_CREATED',
            'RUN_STATUS_CHANGED',
            'RUN_RECOVERED',
            'TICK_ADMITTED',
            'TICK_CLAIMED',
            'TICK_HEARTBEAT',
            'TICK_COMPLETED',
            'TICK_FAILED',
            'LEASE_EXPIRED',
            'PROVIDER_ATTEMPT_STARTED',
            'PROVIDER_ATTEMPT_COMPLETED',
            'EVIDENCE_COMMITTED',
            'CURRENT_EVIDENCE_CHANGED',
            'CHANGE_DECIDED',
            'CHILD_RECORDED'
        )
    ),
    event_time timestamptz NOT NULL,
    fencing_token bigint CHECK (
        fencing_token IS NULL OR fencing_token >= 1
    ),
    payload_json text NOT NULL CHECK (payload_json IS JSON OBJECT),
    FOREIGN KEY (run_id)
        REFERENCES continuous_research_run(run_id) ON DELETE RESTRICT,
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id)
        ON DELETE RESTRICT
);

ALTER TABLE continuous_runtime_tick
ADD CONSTRAINT continuous_runtime_tick_attempt_fkey
FOREIGN KEY (provider_attempt_id, run_id, tick_id)
REFERENCES continuous_provider_attempt(attempt_id, run_id, tick_id)
ON DELETE RESTRICT;

ALTER TABLE continuous_runtime_tick
ADD CONSTRAINT continuous_runtime_tick_evidence_fkey
FOREIGN KEY (evidence_commit_id, run_id, tick_id)
REFERENCES continuous_evidence_commit(evidence_commit_id, run_id, tick_id)
ON DELETE RESTRICT;

ALTER TABLE continuous_runtime_tick
ADD CONSTRAINT continuous_runtime_tick_change_fkey
FOREIGN KEY (change_decision_id, run_id, tick_id)
REFERENCES continuous_change_decision(decision_id, run_id, tick_id)
ON DELETE RESTRICT;

CREATE INDEX continuous_research_run_status_date_idx
ON continuous_research_run(status, trading_date, run_id);
CREATE INDEX continuous_runtime_tick_claimable_idx
ON continuous_runtime_tick(run_id, status, tick_sequence)
WHERE status IN ('PENDING', 'FAILED');
CREATE INDEX continuous_runtime_tick_lease_idx
ON continuous_runtime_tick(status, lease_expires_at, run_id, tick_sequence)
WHERE status = 'IN_PROGRESS';
CREATE INDEX continuous_runtime_tick_attempt_idx
ON continuous_runtime_tick(provider_attempt_id, run_id, tick_id)
WHERE provider_attempt_id IS NOT NULL;
CREATE INDEX continuous_runtime_tick_evidence_idx
ON continuous_runtime_tick(evidence_commit_id, run_id, tick_id)
WHERE evidence_commit_id IS NOT NULL;
CREATE INDEX continuous_runtime_tick_change_idx
ON continuous_runtime_tick(change_decision_id, run_id, tick_id)
WHERE change_decision_id IS NOT NULL;
CREATE INDEX continuous_provider_attempt_status_idx
ON continuous_provider_attempt(run_id, tick_id, status, attempt_number);
CREATE INDEX continuous_evidence_tick_idx
ON continuous_evidence_commit(run_id, tick_id, evidence_commit_id);
CREATE INDEX continuous_evidence_attempt_idx
ON continuous_evidence_commit(attempt_id, run_id, tick_id);
CREATE INDEX continuous_current_evidence_commit_idx
ON continuous_current_evidence(evidence_commit_id, run_id, evidence_scope);
CREATE INDEX continuous_change_attempt_idx
ON continuous_change_decision(provider_attempt_id, run_id, tick_id);
CREATE INDEX continuous_change_evidence_idx
ON continuous_change_decision(evidence_commit_id, run_id, tick_id);
CREATE INDEX continuous_change_previous_evidence_idx
ON continuous_change_decision(previous_evidence_commit_id, run_id)
WHERE previous_evidence_commit_id IS NOT NULL;
CREATE INDEX continuous_child_decision_idx
ON continuous_child_run(decision_id, run_id, tick_id);
CREATE INDEX continuous_runtime_event_history_idx
ON continuous_runtime_event(run_id, tick_id, event_id);

CREATE FUNCTION guard_continuous_research_run_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Continuous Research runs cannot be deleted';
    END IF;
    IF NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.command_hash IS DISTINCT FROM OLD.command_hash
       OR NEW.command_json IS DISTINCT FROM OLD.command_json
       OR NEW.trading_date IS DISTINCT FROM OLD.trading_date
       OR NEW.request_scope_hash IS DISTINCT FROM OLD.request_scope_hash
       OR NEW.policy_id IS DISTINCT FROM OLD.policy_id
       OR NEW.policy_hash IS DISTINCT FROM OLD.policy_hash
       OR NEW.provider_configuration_id IS DISTINCT FROM OLD.provider_configuration_id
       OR NEW.provider_configuration_hash IS DISTINCT FROM OLD.provider_configuration_hash
       OR NEW.research_configuration_id IS DISTINCT FROM OLD.research_configuration_id
       OR NEW.research_configuration_hash IS DISTINCT FROM OLD.research_configuration_hash
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'Continuous Research run identity is immutable';
    END IF;
    IF NEW.version != OLD.version + 1 THEN
        RAISE EXCEPTION 'Continuous Research run version must advance by one';
    END IF;
    IF OLD.status = 'ARCHIVED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Archived Continuous Research run is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER continuous_research_run_no_delete
BEFORE DELETE ON continuous_research_run
FOR EACH ROW EXECUTE FUNCTION guard_continuous_research_run_mutation();
CREATE TRIGGER continuous_research_run_identity_immutable
BEFORE UPDATE ON continuous_research_run
FOR EACH ROW EXECUTE FUNCTION guard_continuous_research_run_mutation();

CREATE FUNCTION guard_continuous_runtime_tick_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Continuous Runtime ticks cannot be deleted';
    END IF;
    IF NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.tick_id IS DISTINCT FROM OLD.tick_id
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.tick_hash IS DISTINCT FROM OLD.tick_hash
       OR NEW.tick_json IS DISTINCT FROM OLD.tick_json
       OR NEW.tick_sequence IS DISTINCT FROM OLD.tick_sequence
       OR NEW.observed_at IS DISTINCT FROM OLD.observed_at
       OR NEW.session_phase IS DISTINCT FROM OLD.session_phase
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'Continuous Runtime tick identity is immutable';
    END IF;
    IF NEW.version != OLD.version + 1 THEN
        RAISE EXCEPTION 'Continuous Runtime tick version must advance by one';
    END IF;
    IF OLD.status IN ('COMPLETED', 'FAILED', 'DATA_BLOCKED')
       AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Terminal Continuous Runtime tick is immutable';
    END IF;
    IF OLD.status = 'IN_PROGRESS' AND NEW.status = 'IN_PROGRESS' AND (
        NEW.claim_id IS DISTINCT FROM OLD.claim_id
        OR NEW.fencing_token IS DISTINCT FROM OLD.fencing_token
    ) THEN
        RAISE EXCEPTION 'Active Continuous Runtime claim cannot be overwritten';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER continuous_runtime_tick_no_delete
BEFORE DELETE ON continuous_runtime_tick
FOR EACH ROW EXECUTE FUNCTION guard_continuous_runtime_tick_mutation();
CREATE TRIGGER continuous_runtime_tick_terminal_immutable
BEFORE UPDATE ON continuous_runtime_tick
FOR EACH ROW EXECUTE FUNCTION guard_continuous_runtime_tick_mutation();

CREATE FUNCTION guard_continuous_provider_attempt_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Continuous Provider Attempts cannot be deleted';
    END IF;
    IF OLD.status != 'STARTED' THEN
        RAISE EXCEPTION 'Terminal Continuous Provider Attempt is immutable';
    END IF;
    IF NEW.attempt_id IS DISTINCT FROM OLD.attempt_id
       OR NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.tick_id IS DISTINCT FROM OLD.tick_id
       OR NEW.attempt_number IS DISTINCT FROM OLD.attempt_number
       OR NEW.claim_id IS DISTINCT FROM OLD.claim_id
       OR NEW.fencing_token IS DISTINCT FROM OLD.fencing_token
       OR NEW.tick_version IS DISTINCT FROM OLD.tick_version
       OR NEW.provider_id IS DISTINCT FROM OLD.provider_id
       OR NEW.product IS DISTINCT FROM OLD.product
       OR NEW.request_hash IS DISTINCT FROM OLD.request_hash
       OR NEW.started_at IS DISTINCT FROM OLD.started_at THEN
        RAISE EXCEPTION 'Continuous Provider Attempt identity is immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER continuous_provider_attempt_no_delete
BEFORE DELETE ON continuous_provider_attempt
FOR EACH ROW EXECUTE FUNCTION guard_continuous_provider_attempt_mutation();
CREATE TRIGGER continuous_provider_attempt_transition_guard
BEFORE UPDATE ON continuous_provider_attempt
FOR EACH ROW EXECUTE FUNCTION guard_continuous_provider_attempt_mutation();

CREATE FUNCTION guard_continuous_current_evidence_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Continuous current Evidence cannot be deleted';
    END IF;
    IF NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.evidence_scope IS DISTINCT FROM OLD.evidence_scope THEN
        RAISE EXCEPTION 'Continuous current Evidence scope is immutable';
    END IF;
    IF NEW.version != OLD.version + 1 THEN
        RAISE EXCEPTION 'Continuous current Evidence version must advance by one';
    END IF;
    IF NEW.last_accepted_fencing_token < OLD.last_accepted_fencing_token THEN
        RAISE EXCEPTION 'Continuous current Evidence fencing token cannot regress';
    END IF;
    IF NEW.evidence_commit_id = OLD.evidence_commit_id
       OR NEW.material_identity_hash = OLD.material_identity_hash THEN
        RAISE EXCEPTION 'Identical Evidence must not advance current Evidence';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER continuous_current_evidence_no_delete
BEFORE DELETE ON continuous_current_evidence
FOR EACH ROW EXECUTE FUNCTION guard_continuous_current_evidence_mutation();
CREATE TRIGGER continuous_current_evidence_transition_guard
BEFORE UPDATE ON continuous_current_evidence
FOR EACH ROW EXECUTE FUNCTION guard_continuous_current_evidence_mutation();

CREATE TRIGGER continuous_evidence_commit_no_update
BEFORE UPDATE ON continuous_evidence_commit
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_evidence_commit_no_delete
BEFORE DELETE ON continuous_evidence_commit
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_change_decision_no_update
BEFORE UPDATE ON continuous_change_decision
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_change_decision_no_delete
BEFORE DELETE ON continuous_change_decision
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_child_run_no_update
BEFORE UPDATE ON continuous_child_run
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_child_run_no_delete
BEFORE DELETE ON continuous_child_run
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_runtime_event_no_update
BEFORE UPDATE ON continuous_runtime_event
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER continuous_runtime_event_no_delete
BEFORE DELETE ON continuous_runtime_event
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
