CREATE TABLE shadow_research_session (
    session_id text PRIMARY KEY,
    session_hash text NOT NULL UNIQUE CHECK (
        session_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    idempotency_key text NOT NULL UNIQUE,
    run_id text NOT NULL UNIQUE REFERENCES continuous_research_run(run_id),
    trading_date date NOT NULL,
    runtime_mode text NOT NULL CHECK (runtime_mode = 'SHADOW'),
    command_json jsonb NOT NULL CHECK (
        jsonb_typeof(command_json) = 'object'
        AND command_json->>'schema_version' = 'shadow-session-command/v1'
    ),
    status text NOT NULL CHECK (status IN (
        'SCHEDULED', 'RUNNING', 'FROZEN', 'OUTCOME_PENDING',
        'SETTLED', 'FAILED', 'INVALIDATED'
    )),
    outcome_status text NOT NULL CHECK (outcome_status IN (
        'NOT_EXPECTED', 'PENDING', 'SETTLED', 'UNAVAILABLE', 'INVALIDATED'
    )),
    decision_id text UNIQUE,
    version bigint NOT NULL CHECK (version >= 1),
    reason_codes_json jsonb NOT NULL CHECK (
        jsonb_typeof(reason_codes_json) = 'array'
    ),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    finished_at timestamptz,
    CHECK ((status IN ('SETTLED', 'FAILED', 'INVALIDATED')) =
           (finished_at IS NOT NULL)),
    CHECK (status NOT IN ('FROZEN', 'OUTCOME_PENDING', 'SETTLED')
           OR decision_id IS NOT NULL),
    CHECK (status NOT IN ('SCHEDULED', 'RUNNING') OR decision_id IS NULL),
    CHECK (decision_id IS NOT NULL OR outcome_status IN (
        'NOT_EXPECTED', 'INVALIDATED'
    )),
    CHECK (decision_id IS NULL OR outcome_status != 'NOT_EXPECTED')
);

CREATE TABLE shadow_research_decision (
    decision_id text PRIMARY KEY,
    decision_hash text NOT NULL UNIQUE CHECK (
        decision_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    session_id text NOT NULL UNIQUE
        REFERENCES shadow_research_session(session_id) ON DELETE RESTRICT,
    run_id text NOT NULL,
    tick_id text NOT NULL,
    summary_id text NOT NULL UNIQUE
        REFERENCES research_daily_summary(summary_id) ON DELETE RESTRICT,
    summary_hash text NOT NULL CHECK (
        summary_hash ~ '^sha256:[0-9a-f]{64}$'
    ),
    decision_time timestamptz NOT NULL,
    decision_frozen_at timestamptz NOT NULL,
    payload_json jsonb NOT NULL CHECK (
        jsonb_typeof(payload_json) = 'object'
        AND payload_json->>'schema_version' = 'shadow-decision/v1'
    ),
    created_at timestamptz NOT NULL,
    FOREIGN KEY (run_id, tick_id)
        REFERENCES continuous_runtime_tick(run_id, tick_id) ON DELETE RESTRICT,
    CHECK (decision_frozen_at >= decision_time),
    CHECK (created_at = decision_frozen_at)
);

ALTER TABLE shadow_research_session
ADD CONSTRAINT shadow_research_session_decision_fkey
FOREIGN KEY (decision_id)
REFERENCES shadow_research_decision(decision_id) ON DELETE RESTRICT
DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE shadow_research_event (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL
        REFERENCES shadow_research_session(session_id) ON DELETE RESTRICT,
    decision_id text REFERENCES shadow_research_decision(decision_id)
        ON DELETE RESTRICT,
    event_type text NOT NULL CHECK (event_type IN (
        'SESSION_SCHEDULED', 'SESSION_RUNNING', 'DECISION_FROZEN',
        'OUTCOME_PENDING', 'SESSION_SETTLED', 'SESSION_FAILED',
        'SESSION_INVALIDATED', 'SESSION_RECOVERED'
    )),
    from_status text,
    to_status text NOT NULL,
    expected_version bigint CHECK (expected_version IS NULL OR expected_version >= 1),
    resulting_version bigint NOT NULL CHECK (resulting_version >= 1),
    reason_codes_json jsonb NOT NULL CHECK (
        jsonb_typeof(reason_codes_json) = 'array'
    ),
    event_time timestamptz NOT NULL,
    payload_json jsonb NOT NULL CHECK (jsonb_typeof(payload_json) = 'object')
);

CREATE INDEX shadow_research_session_status_idx
ON shadow_research_session(status, trading_date, session_id);

CREATE INDEX shadow_research_event_history_idx
ON shadow_research_event(session_id, event_id);

CREATE INDEX shadow_research_decision_tick_idx
ON shadow_research_decision(run_id, tick_id);

CREATE INDEX shadow_research_event_decision_idx
ON shadow_research_event(decision_id)
WHERE decision_id IS NOT NULL;

CREATE FUNCTION guard_shadow_research_session_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Shadow Sessions cannot be deleted';
    END IF;
    IF NEW.session_id IS DISTINCT FROM OLD.session_id
       OR NEW.session_hash IS DISTINCT FROM OLD.session_hash
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.run_id IS DISTINCT FROM OLD.run_id
       OR NEW.trading_date IS DISTINCT FROM OLD.trading_date
       OR NEW.runtime_mode IS DISTINCT FROM OLD.runtime_mode
       OR NEW.command_json IS DISTINCT FROM OLD.command_json
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'Shadow Session identity is immutable';
    END IF;
    IF NEW.version != OLD.version + 1 THEN
        RAISE EXCEPTION 'Shadow Session version must advance by one';
    END IF;
    IF OLD.decision_id IS NOT NULL
       AND NEW.decision_id IS DISTINCT FROM OLD.decision_id THEN
        RAISE EXCEPTION 'Frozen Shadow Decision cannot change';
    END IF;
    IF NOT (
        (OLD.status = 'SCHEDULED' AND NEW.status IN ('RUNNING', 'FAILED', 'INVALIDATED'))
        OR (OLD.status = 'RUNNING' AND NEW.status IN ('FROZEN', 'FAILED', 'INVALIDATED'))
        OR (OLD.status = 'FROZEN' AND NEW.status IN ('OUTCOME_PENDING', 'INVALIDATED'))
        OR (OLD.status = 'OUTCOME_PENDING' AND NEW.status IN ('SETTLED', 'FAILED', 'INVALIDATED'))
        OR (OLD.status = 'FAILED' AND NEW.status IN ('RUNNING', 'INVALIDATED'))
    ) THEN
        RAISE EXCEPTION 'Invalid Shadow Session state transition';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER shadow_research_session_guard
BEFORE UPDATE OR DELETE ON shadow_research_session
FOR EACH ROW EXECUTE FUNCTION guard_shadow_research_session_mutation();

CREATE TRIGGER shadow_research_decision_no_update
BEFORE UPDATE OR DELETE ON shadow_research_decision
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

CREATE TRIGGER shadow_research_event_no_update
BEFORE UPDATE OR DELETE ON shadow_research_event
FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
