"""Existing Backtest UoW owns reservation/opening facts and their receipts."""

from typing import Any, Protocol
from uuid import UUID

from market_regime_alpha.research_qualification.domain.backtest_holdout import BacktestHoldoutOpening, BacktestHoldoutReservation


class BacktestHoldoutRepository(Protocol):
    def reserve(self, request: BacktestHoldoutReservation) -> dict[str, Any]: ...
    def open(self, request: BacktestHoldoutOpening) -> dict[str, Any]: ...
    def record(self, reservation_id: UUID, *, opening: bool) -> dict[str, Any]: ...


class BacktestHoldoutReadPort(Protocol):
    def reservation(self, reservation_id: UUID) -> BacktestHoldoutReservation: ...
    def inspect(self, reservation_id: UUID) -> dict[str, Any]: ...
    def execution_blockers(self, run_id: UUID) -> tuple[str, ...]: ...
    def development_evaluation_roster(self, run_id: UUID) -> tuple[tuple[str, str, str, str], ...]: ...
    def model_features(self, model_id: UUID) -> tuple[tuple[UUID, str], ...]: ...
