"""Session lock and short read-only SQL for the prospective process guard."""

from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar
from datetime import datetime
from typing import Any, Iterator, cast
from uuid import UUID, uuid5

import psycopg
from psycopg.rows import dict_row

_ADMISSION_KEY = "runtime:prospective-operation-admission"
_DATABASE_WRITER_KEY = "operator:prospective-database-writer"
_operation_session: ContextVar[PostgresProspectiveOperationSession | None] = ContextVar(
    "prospective_operation_session", default=None,
)


def _admission_lock(connection: psycopg.Connection[Any]) -> None:
    # All target Runtime Attempt creation paths and supervisor acquisition use
    # this same transaction lock. It is never held over Provider I/O.
    connection.execute("SELECT pg_advisory_xact_lock(hashtextextended(%s,0))", (_ADMISSION_KEY,))


def _writer_pid(connection: psycopg.Connection[Any]) -> int | None:
    row = connection.execute(
        """WITH intent AS (SELECT hashtextextended(%s,0) AS key)
           SELECT pid FROM pg_locks, intent
           WHERE locktype='advisory' AND granted AND mode='ExclusiveLock'
             AND database=(SELECT oid FROM pg_database WHERE datname=current_database())
             AND classid::bigint=((intent.key >> 32) & 4294967295)
             AND objid::bigint=(intent.key & 4294967295) AND objsubid=1""",
        (_DATABASE_WRITER_KEY,),
    ).fetchone()
    return None if row is None else int(row[0])


def admit_runtime_attempt(connection: psycopg.Connection[Any], *, run_id: UUID | None,
                          step_id: UUID | None = None) -> None:
    """Atomic operational exclusion shared by every current target Runtime claim.

    This is process admission, not a new lease/Authority. Current Runtime still
    owns the Attempt/fence and result transaction. Old/nonparticipating clients
    must be excluded by deployment preflight; advisory locks do not fence SQL
    issued by arbitrary database credentials.
    """
    _admission_lock(connection)
    owner = _writer_pid(connection)
    session = _operation_session.get()
    if session is None:
        if owner is not None:
            raise ValueError("OPERATION_RUNTIME_ADMISSION_CONFLICT")
        return
    session.require_supervisor_lock(session.series_code)
    if owner != session.connection.info.backend_pid:
        raise ValueError("OPERATION_RUNTIME_ADMISSION_CONFLICT")
    scope = connection.execute(
        "SELECT oid::bigint, (pg_control_system()).system_identifier::text "
        "FROM pg_database WHERE datname=current_database()",
    ).fetchone()
    if scope != (session.database_oid, session.cluster_identity):
        raise ValueError("OPERATION_RUNTIME_ADMISSION_SCOPE_MISMATCH")
    if run_id is None and step_id is not None:
        row = connection.execute("SELECT run_id FROM mra.runtime_step WHERE step_id=%s", (step_id,)).fetchone()
        run_id = None if row is None else row[0]
    allowed = connection.execute(
        """SELECT 1 FROM mra.runtime_run AS run
           JOIN mra.runtime_schedule AS schedule USING (schedule_id)
           WHERE run.run_id=%s AND schedule.schedule_code='prospective-archive'
             AND run.fire_key LIKE 'archive:%%'
             AND NOT EXISTS (SELECT 1 FROM mra.runtime_step AS step WHERE step.run_id=run.run_id
                             AND step.implementation NOT LIKE 'market.prospective_archive.%%')
             AND NOT EXISTS (SELECT 1 FROM mra.prospective_archive_generation AS generation
                             WHERE run.fire_key LIKE 'archive:' || generation.market_archive_id::text || ':%%'
                               AND generation.series_code<>%s)""", (run_id, session.series_code),
    ).fetchone()
    if allowed is None and not session.daily_run_matches(connection,run_id) and not session.backtest_run_matches(connection,run_id):
        raise ValueError("OPERATION_RUNTIME_RUN_OUTSIDE_SERIES")
    if session.has_conflicting_attempts(session.series_code):
        raise ValueError("OPERATION_ACTIVE_ATTEMPT_CONFLICT")


def remember_operational_attempt(attempt_id: UUID) -> None:
    session = _operation_session.get()
    if session is not None:
        # IDs are generated by the canonical Runtime writer, never by worker-id
        # text. Rolled-back IDs match no row; commit-unknown is owner-reconciled.
        session.own_attempt_ids.add(attempt_id)


class PostgresProspectiveOperationSession:
    def __init__(self, connection: psycopg.Connection[Any]) -> None:
        self.connection = connection
        self.series_code = ""
        self.database_oid = 0
        self.cluster_identity = ""
        self.own_attempt_ids: set[UUID] = set()
        self.daily_scope: tuple[UUID,str,str,str | None,int] | None = None
        self.backtest_scope: tuple[UUID,str] | None = None
        self.daily_recovery_scope: tuple[UUID, str] | None = None

    def allow_expired_daily_recovery(self, use_id: UUID, code_sha: str) -> None:
        """Called only after the operator template's canonical model/config checks.

        This admits inspection/recovery of expired safe-effect steps; it grants
        no claim capability. Each new claim still needs its exact daily handoff.
        """
        self.require_supervisor_lock(self.series_code)
        self.daily_recovery_scope = (use_id, code_sha)

    def backtest_run_matches(self, connection: psycopg.Connection[Any], run_id: UUID | None) -> bool:
        if self.backtest_scope is None or run_id is None:
            return False
        identity, digest = self.backtest_scope
        return connection.execute("""SELECT EXISTS(SELECT 1 FROM mra.backtest_runtime_binding binding
            JOIN mra.exploratory_backtest_run backtest USING(exploratory_backtest_run_id)
            JOIN mra.runtime_run run ON run.run_id=binding.runtime_run_id
            WHERE run.run_id=%s AND binding.exploratory_backtest_run_id=%s
              AND binding.specification_sha256=%s AND backtest.current_specification_sha256=%s
              AND run.runtime_mode='HISTORICAL'
              AND NOT EXISTS(SELECT 1 FROM mra.runtime_step step WHERE step.run_id=run.run_id
                AND step.implementation<>%s))""", (run_id,identity,digest,digest,
                'market_regime_alpha.research_qualification.application.backtest_runtime:BacktestRuntimeActionExecutor')).fetchone()==(True,)

    def daily_run_matches(self, connection: psycopg.Connection[Any], run_id: UUID | None) -> bool:
        if self.daily_scope is None or run_id is None:
            return False
        identity,code,config,phase,round_no=self.daily_scope
        allowed={uuid5(identity,'prediction-runtime'):('daily:'+str(identity),'research.daily_prediction.'),
                 uuid5(identity,'outcome-evaluation-runtime'):('daily-outcome:'+str(identity),'research.daily_outcome.'),
                 uuid5(identity,'abstention-runtime'):('daily-abstention:'+str(identity),'research.daily_abstention.')}
        if phase is not None:
            allowed={uuid5(identity,phase+'-collection:'+str(round_no)):
                ('daily-'+phase+':'+str(identity)+':round:'+str(round_no),'market.daily_research.'+phase+'.')}
        if run_id not in allowed:
            return False
        fire,prefix=allowed[run_id]
        return connection.execute("""SELECT EXISTS(SELECT 1 FROM mra.runtime_run run
            WHERE run.run_id=%s AND run.runtime_mode='SHADOW' AND run.fire_key=%s AND run.code_sha=%s AND run.config_hash=%s
              AND EXISTS(SELECT 1 FROM mra.runtime_step step WHERE step.run_id=run.run_id)
              AND NOT EXISTS(SELECT 1 FROM mra.runtime_step step WHERE step.run_id=run.run_id
                AND step.implementation NOT LIKE %s))""",(run_id,fire,code,config,prefix+'%')).fetchone()==(True,)

    def snapshot(self) -> dict[str, Any]:
        from market_regime_alpha.infrastructure.postgres.queries.evidence import read_evidence_snapshot

        with self.connection.transaction():
            self.connection.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")
            return read_evidence_snapshot(self.connection)

    def require_supervisor_lock(self, series_code: str) -> None:
        if self.connection.closed:
            raise ValueError("OPERATION_SUPERVISOR_CONNECTION_LOST")
        try:
            row = self.connection.execute(
                """WITH intent AS (SELECT hashtextextended(%s,0) AS key)
                   SELECT EXISTS (SELECT 1 FROM pg_locks, intent
                     WHERE pid=pg_backend_pid() AND locktype='advisory' AND granted
                       AND classid::bigint=((intent.key >> 32) & 4294967295)
                       AND objid::bigint=(intent.key & 4294967295) AND objsubid=1)""",
                ("operator:prospective-series:" + series_code,),
            ).fetchone()
        except psycopg.Error as exc:
            raise ValueError("OPERATION_SUPERVISOR_CONNECTION_LOST") from exc
        if row != (True,):
            raise ValueError("OPERATION_SUPERVISOR_LOCK_LOST")
        if _writer_pid(self.connection) != self.connection.info.backend_pid:
            raise ValueError("OPERATION_SUPERVISOR_LOCK_LOST")

    def has_conflicting_attempts(self, series_code: str) -> bool:
        expired_daily: list[UUID] = []
        if self.daily_recovery_scope is not None:
            use_id, code = self.daily_recovery_scope
            schedules = ['daily-model-'+use_id.hex, 'daily-outcome-'+use_id.hex,
                         'daily-abstention-'+use_id.hex, 'daily-input-collection-'+use_id.hex,
                         'daily-outcome-collection-'+use_id.hex]
            expired_daily.extend(row[0] for row in self.connection.execute("""
                SELECT run.run_id FROM mra.runtime_run run
                JOIN mra.runtime_schedule schedule USING(schedule_id)
                WHERE schedule.schedule_code=ANY(%s::text[]) AND run.code_sha=%s
                  AND run.runtime_mode='SHADOW'
                  AND NOT EXISTS(SELECT 1 FROM mra.runtime_step step WHERE step.run_id=run.run_id
                    AND NOT (step.implementation LIKE 'research.daily_prediction.%%'
                      OR step.implementation LIKE 'research.daily_outcome.%%'
                      OR step.implementation LIKE 'research.daily_abstention.%%'
                      OR step.implementation LIKE 'market.daily_research.%%'))
                """, (schedules, code)).fetchall())
        if self.daily_scope is not None:
            suffixes=('prediction-runtime','outcome-evaluation-runtime','abstention-runtime') if self.daily_scope[3] is None else (self.daily_scope[3]+'-collection:'+str(self.daily_scope[4]),)
            for suffix in suffixes:
                identity=uuid5(self.daily_scope[0],suffix)
                if self.daily_run_matches(self.connection,identity):
                    expired_daily.append(identity)
        row = self.connection.execute(
            """SELECT count(*) FROM mra.runtime_attempt AS attempt
               JOIN mra.runtime_step AS step USING (step_id)
               JOIN mra.runtime_run AS run ON run.run_id=step.run_id
               WHERE attempt.state IN ('CLAIMED','RUNNING')
                 AND NOT (attempt.attempt_id = ANY(%s::uuid[]))
                 AND (attempt.lease_until > clock_timestamp() OR NOT EXISTS (
                   SELECT 1 FROM mra.prospective_archive_generation AS generation
                   WHERE generation.series_code=%s
                     AND run.fire_key LIKE 'archive:' || generation.market_archive_id::text || ':%%'
                 ) AND NOT (run.run_id=ANY(%s::uuid[]) AND step.external_effect_class IN ('NONE','CONTENT_PUT')))""", (list(self.own_attempt_ids), series_code, expired_daily),
        ).fetchone()
        return row is None or bool(row[0])

    def clock(self) -> datetime:
        row = self.connection.execute("SELECT clock_timestamp()").fetchone()
        if row is None:
            raise ValueError("OPERATION_DATABASE_CLOCK_UNAVAILABLE")
        return cast(datetime, row[0])

    def generations(self, series_code: str) -> list[dict[str, Any]]:
        with self.connection.transaction(), self.connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute("SET TRANSACTION READ ONLY")
            return cursor.execute(
                "SELECT * FROM mra.prospective_archive_generation WHERE series_code=%s ORDER BY generation",
                (series_code,),
            ).fetchall()


@contextmanager
def prospective_operation_session(
    database_url: str, *, database_name: str, database_oid: int,
    cluster_identity: str, series_code: str,
) -> Iterator[PostgresProspectiveOperationSession]:
    """Bind one advisory lock to one session without spanning a transaction."""
    with psycopg.connect(database_url, autocommit=True,
                         application_name="mra-prospective-supervisor") as connection:
        row = connection.execute(
            "SELECT current_database(), oid::bigint, (pg_control_system()).system_identifier::text "
            "FROM pg_database WHERE datname=current_database()",
        ).fetchone()
        if row != (database_name, database_oid, cluster_identity):
            raise ValueError("OPERATION_DATABASE_IDENTITY_MISMATCH")
        key = "operator:prospective-series:" + series_code
        with connection.transaction():
            _admission_lock(connection)
            locked = connection.execute("SELECT pg_try_advisory_lock(hashtextextended(%s,0))", (key,)).fetchone()
            database_locked = connection.execute(
                "SELECT pg_try_advisory_lock(hashtextextended(%s,0))", (_DATABASE_WRITER_KEY,),
            ).fetchone()
            if locked != (True,) or database_locked != (True,):
                raise ValueError("OPERATION_DUPLICATE_SUPERVISOR")
        session = PostgresProspectiveOperationSession(connection)
        session.series_code, session.database_oid, session.cluster_identity = series_code, database_oid, cluster_identity
        token = _operation_session.set(session)
        try:
            yield session
        finally:
            _operation_session.reset(token)
            if not connection.closed:
                connection.execute("SELECT pg_advisory_unlock(hashtextextended(%s,0))", (key,))
                connection.execute("SELECT pg_advisory_unlock(hashtextextended(%s,0))", (_DATABASE_WRITER_KEY,))


@contextmanager
def daily_research_admission(*, prediction_id: UUID, code_sha: str, config_sha256: str, collection_phase: str | None=None, collection_round: int=1) -> Iterator[None]:
    """Sequential handoff inside the existing supervisor, bound to two exact Runs.

    No lock is released; other Runtime workers remain excluded by atomic admission.
    This process capability is not a business registration or execution Authority.
    """
    if collection_phase not in {None,'input','outcome'} or not 1<=collection_round<=16:
        raise ValueError('DAILY_OPERATION_SCOPE_INVALID')
    session=_operation_session.get()
    if session is None:
        raise ValueError('DAILY_OPERATION_REQUIRES_SUPERVISOR')
    session.require_supervisor_lock(session.series_code)
    if session.daily_scope is not None or session.backtest_scope is not None:
        raise ValueError('DAILY_OPERATION_NESTED_HANDOFF')
    with session.connection.transaction():
        _admission_lock(session.connection)
        if session.connection.execute("SELECT EXISTS(SELECT 1 FROM mra.runtime_attempt WHERE state IN ('CLAIMED','RUNNING') AND lease_until>clock_timestamp())").fetchone()!=(False,):
            raise ValueError('OPERATION_ACTIVE_ATTEMPT_CONFLICT')
        session.daily_scope=(prediction_id,code_sha,config_sha256,collection_phase,collection_round)
    try:
        if session.has_conflicting_attempts(session.series_code):
            raise ValueError('OPERATION_ACTIVE_ATTEMPT_CONFLICT')
        yield
    finally:
        session.daily_scope=None


@contextmanager
def backtest_research_admission(*, backtest_run_id: UUID, specification_sha256: str) -> Iterator[None]:
    """Planned Generic research uses the same reservation during collection pause."""
    session = _operation_session.get()
    if session is None:
        raise ValueError('BACKTEST_OPERATION_REQUIRES_SUPERVISOR')
    session.require_supervisor_lock(session.series_code)
    if session.daily_scope is not None or session.backtest_scope is not None:
        raise ValueError('BACKTEST_OPERATION_NESTED_HANDOFF')
    with session.connection.transaction():
        _admission_lock(session.connection)
        if session.connection.execute("SELECT EXISTS(SELECT 1 FROM mra.runtime_attempt WHERE state IN ('CLAIMED','RUNNING'))").fetchone()!=(False,):
            raise ValueError('OPERATION_ACTIVE_ATTEMPT_CONFLICT')
        if session.connection.execute('SELECT current_specification_sha256 FROM mra.exploratory_backtest_run WHERE exploratory_backtest_run_id=%s', (backtest_run_id,)).fetchone()!=(specification_sha256,):
            raise ValueError('BACKTEST_OPERATION_SPECIFICATION_MISMATCH')
        session.backtest_scope=(backtest_run_id,specification_sha256)
    try:
        yield
    finally:
        session.backtest_scope=None
