"""Session lock and short read-only SQL for the prospective process guard."""

from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar
from datetime import datetime
from typing import Any, Iterator, cast
from uuid import UUID

import psycopg
from psycopg.rows import dict_row

from market_regime_alpha.infrastructure.postgres.queries.evidence import read_evidence_snapshot


_ADMISSION_KEY = "runtime:prospective-operation-admission"
_DATABASE_WRITER_KEY = "operator:prospective-database-writer"
_operation_session: ContextVar[PostgresProspectiveOperationSession | None] = ContextVar(
    "prospective_operation_session", default=None,
)


def _admission_lock(connection: psycopg.Connection[Any]) -> None:
    # All target Runtime Attempt creation paths and supervisor acquisition use
    # this same transaction lock. It is never held over Provider I/O.
    connection.execute("SELECT pg_advisory_xact_lock(hashtextextended(%s,0))", (_ADMISSION_KEY,))


def _writer_pid(connection: psycopg.Connection[Any]) -> int | None:
    row = connection.execute(
        """WITH intent AS (SELECT hashtextextended(%s,0) AS key)
           SELECT pid FROM pg_locks, intent
           WHERE locktype='advisory' AND granted AND mode='ExclusiveLock'
             AND database=(SELECT oid FROM pg_database WHERE datname=current_database())
             AND classid::bigint=((intent.key >> 32) & 4294967295)
             AND objid::bigint=(intent.key & 4294967295) AND objsubid=1""",
        (_DATABASE_WRITER_KEY,),
    ).fetchone()
    return None if row is None else int(row[0])


def admit_runtime_attempt(connection: psycopg.Connection[Any], *, run_id: UUID | None,
                          step_id: UUID | None = None) -> None:
    """Atomic operational exclusion shared by every current target Runtime claim.

    This is process admission, not a new lease/Authority. Current Runtime still
    owns the Attempt/fence and result transaction. Old/nonparticipating clients
    must be excluded by deployment preflight; advisory locks do not fence SQL
    issued by arbitrary database credentials.
    """
    _admission_lock(connection)
    owner = _writer_pid(connection)
    session = _operation_session.get()
    if session is None:
        if owner is not None:
            raise ValueError("OPERATION_RUNTIME_ADMISSION_CONFLICT")
        return
    session.require_supervisor_lock(session.series_code)
    if owner != session.connection.info.backend_pid:
        raise ValueError("OPERATION_RUNTIME_ADMISSION_CONFLICT")
    scope = connection.execute(
        "SELECT oid::bigint, (pg_control_system()).system_identifier::text "
        "FROM pg_database WHERE datname=current_database()",
    ).fetchone()
    if scope != (session.database_oid, session.cluster_identity):
        raise ValueError("OPERATION_RUNTIME_ADMISSION_SCOPE_MISMATCH")
    if run_id is None and step_id is not None:
        row = connection.execute("SELECT run_id FROM mra.runtime_step WHERE step_id=%s", (step_id,)).fetchone()
        run_id = None if row is None else row[0]
    allowed = connection.execute(
        """SELECT 1 FROM mra.runtime_run AS run
           JOIN mra.runtime_schedule AS schedule USING (schedule_id)
           WHERE run.run_id=%s AND schedule.schedule_code='prospective-archive'
             AND run.fire_key LIKE 'archive:%%'
             AND NOT EXISTS (SELECT 1 FROM mra.runtime_step AS step WHERE step.run_id=run.run_id
                             AND step.implementation NOT LIKE 'market.prospective_archive.%%')
             AND NOT EXISTS (SELECT 1 FROM mra.prospective_archive_generation AS generation
                             WHERE run.fire_key LIKE 'archive:' || generation.market_archive_id::text || ':%%'
                               AND generation.series_code<>%s)""", (run_id, session.series_code),
    ).fetchone()
    if allowed is None:
        raise ValueError("OPERATION_RUNTIME_RUN_OUTSIDE_SERIES")
    if session.has_conflicting_attempts(session.series_code):
        raise ValueError("OPERATION_ACTIVE_ATTEMPT_CONFLICT")


def remember_operational_attempt(attempt_id: UUID) -> None:
    session = _operation_session.get()
    if session is not None:
        # IDs are generated by the canonical Runtime writer, never by worker-id
        # text. Rolled-back IDs match no row; commit-unknown is owner-reconciled.
        session.own_attempt_ids.add(attempt_id)


class PostgresProspectiveOperationSession:
    def __init__(self, connection: psycopg.Connection[Any]) -> None:
        self.connection = connection
        self.series_code = ""
        self.database_oid = 0
        self.cluster_identity = ""
        self.own_attempt_ids: set[UUID] = set()

    def snapshot(self) -> dict[str, Any]:
        with self.connection.transaction():
            self.connection.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")
            return read_evidence_snapshot(self.connection)

    def require_supervisor_lock(self, series_code: str) -> None:
        if self.connection.closed:
            raise ValueError("OPERATION_SUPERVISOR_CONNECTION_LOST")
        try:
            row = self.connection.execute(
                """WITH intent AS (SELECT hashtextextended(%s,0) AS key)
                   SELECT EXISTS (SELECT 1 FROM pg_locks, intent
                     WHERE pid=pg_backend_pid() AND locktype='advisory' AND granted
                       AND classid::bigint=((intent.key >> 32) & 4294967295)
                       AND objid::bigint=(intent.key & 4294967295) AND objsubid=1)""",
                ("operator:prospective-series:" + series_code,),
            ).fetchone()
        except psycopg.Error as exc:
            raise ValueError("OPERATION_SUPERVISOR_CONNECTION_LOST") from exc
        if row != (True,):
            raise ValueError("OPERATION_SUPERVISOR_LOCK_LOST")
        if _writer_pid(self.connection) != self.connection.info.backend_pid:
            raise ValueError("OPERATION_SUPERVISOR_LOCK_LOST")

    def has_conflicting_attempts(self, series_code: str) -> bool:
        row = self.connection.execute(
            """SELECT count(*) FROM mra.runtime_attempt AS attempt
               JOIN mra.runtime_step AS step USING (step_id)
               JOIN mra.runtime_run AS run ON run.run_id=step.run_id
               WHERE attempt.state IN ('CLAIMED','RUNNING')
                 AND NOT (attempt.attempt_id = ANY(%s::uuid[]))
                 AND (attempt.lease_until > clock_timestamp() OR NOT EXISTS (
                   SELECT 1 FROM mra.prospective_archive_generation AS generation
                   WHERE generation.series_code=%s
                     AND run.fire_key LIKE 'archive:' || generation.market_archive_id::text || ':%%'
                 ))""", (list(self.own_attempt_ids), series_code),
        ).fetchone()
        return row is None or bool(row[0])

    def clock(self) -> datetime:
        row = self.connection.execute("SELECT clock_timestamp()").fetchone()
        if row is None:
            raise ValueError("OPERATION_DATABASE_CLOCK_UNAVAILABLE")
        return cast(datetime, row[0])

    def generations(self, series_code: str) -> list[dict[str, Any]]:
        with self.connection.transaction(), self.connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute("SET TRANSACTION READ ONLY")
            return cursor.execute(
                "SELECT * FROM mra.prospective_archive_generation WHERE series_code=%s ORDER BY generation",
                (series_code,),
            ).fetchall()


@contextmanager
def prospective_operation_session(
    database_url: str, *, database_name: str, database_oid: int,
    cluster_identity: str, series_code: str,
) -> Iterator[PostgresProspectiveOperationSession]:
    """Bind one advisory lock to one session without spanning a transaction."""
    with psycopg.connect(database_url, autocommit=True,
                         application_name="mra-prospective-supervisor") as connection:
        row = connection.execute(
            "SELECT current_database(), oid::bigint, (pg_control_system()).system_identifier::text "
            "FROM pg_database WHERE datname=current_database()",
        ).fetchone()
        if row != (database_name, database_oid, cluster_identity):
            raise ValueError("OPERATION_DATABASE_IDENTITY_MISMATCH")
        key = "operator:prospective-series:" + series_code
        with connection.transaction():
            _admission_lock(connection)
            locked = connection.execute("SELECT pg_try_advisory_lock(hashtextextended(%s,0))", (key,)).fetchone()
            database_locked = connection.execute(
                "SELECT pg_try_advisory_lock(hashtextextended(%s,0))", (_DATABASE_WRITER_KEY,),
            ).fetchone()
            if locked != (True,) or database_locked != (True,):
                raise ValueError("OPERATION_DUPLICATE_SUPERVISOR")
        session = PostgresProspectiveOperationSession(connection)
        session.series_code, session.database_oid, session.cluster_identity = series_code, database_oid, cluster_identity
        token = _operation_session.set(session)
        try:
            yield session
        finally:
            _operation_session.reset(token)
            if not connection.closed:
                connection.execute("SELECT pg_advisory_unlock(hashtextextended(%s,0))", (key,))
                connection.execute("SELECT pg_advisory_unlock(hashtextextended(%s,0))", (_DATABASE_WRITER_KEY,))
