"""Research-only Signal Layer contracts, model and immutable replay boundary."""

from market_regime_alpha.signals.artifact import (
    load_verified_signal_run,
    publish_signal_run,
    replay_signal_run,
)
from market_regime_alpha.signals.contracts import (
    ConfirmationState,
    SignalFamily,
    SignalSnapshot,
    SignalState,
)
from market_regime_alpha.signals.engine import (
    SIGNAL_MODEL_CONFIG_SCHEMA,
    SIGNAL_OBSERVATION_SCHEMA,
    SignalModelConfig,
    SignalObservation,
    SignalRunArtifact,
    run_signal_model,
)
from market_regime_alpha.signals.input_assembly import (
    SIGNAL_INPUT_MAPPING_CONFIGURATION_SCHEMA,
    SIGNAL_OBSERVATION_V2_SCHEMA,
    SignalFactorMapping,
    SignalFactorName,
    SignalFactorObservation,
    SignalInputAssembler,
    SignalInputMappingConfiguration,
    SignalObservationV2,
    canonical_signal_input_mapping,
)
from market_regime_alpha.signals.model_contracts import (
    SignalMeaning,
    SignalModel,
    SignalModelRequest,
    SignalModelResult,
)
from market_regime_alpha.signals.v2 import (
    SIGNAL_RUN_V2_SCHEMA,
    SignalRunArtifactV2,
    VerifiedSignalRunArtifactV2,
    load_verified_signal_run_v2,
    publish_signal_run_v2,
    replay_signal_run_v2,
    run_signal_model_v2,
)
from market_regime_alpha.signals.candidate_view import (
    CandidateFeatureView,
    load_candidate_feature_view,
    publish_candidate_feature_view,
)
from market_regime_alpha.signals.candidate_view_v2 import (
    CandidateFeatureViewV2,
    load_candidate_feature_view_v2,
    publish_candidate_feature_view_v2,
)
from market_regime_alpha.signals.decimal_model import (
    CANONICAL_SIGNAL_MODEL_ID,
    CANONICAL_SIGNAL_MODEL_VERSION,
    CanonicalSignalModelV2,
    CanonicalSignalSnapshotV3,
    SignalModelConfigurationV2,
    canonical_signal_model_configuration_v2,
)
from market_regime_alpha.signals.input_v3 import (
    SignalFactorMappingV2,
    SignalInputAssemblerV3,
    SignalInputMappingConfigurationV2,
    SignalObservationV3,
    canonical_signal_input_mapping_v2,
)
from market_regime_alpha.signals.governance import (
    CANONICAL_SIGNAL_TARGET_ID,
    canonical_signal_model_definition,
    persist_canonical_signal_model_for_research,
    register_canonical_signal_model_for_research,
)
from market_regime_alpha.signals.policies import (
    SignalFactorFreshnessPolicy,
    SignalFactorRequirementMode,
    SignalFactorRequirementPolicy,
    canonical_all_factors_required_policy,
    canonical_signal_freshness_policy,
)
from market_regime_alpha.signals.v3 import (
    SIGNAL_RUN_V3_SCHEMA,
    SignalRunArtifactV3,
    VerifiedSignalRunArtifactV3,
    load_verified_signal_run_v3,
    publish_signal_run_v3,
    replay_signal_run_v3,
    run_signal_model_v3,
)

__all__ = [
    "SIGNAL_MODEL_CONFIG_SCHEMA",
    "SIGNAL_INPUT_MAPPING_CONFIGURATION_SCHEMA",
    "SIGNAL_OBSERVATION_SCHEMA",
    "SIGNAL_OBSERVATION_V2_SCHEMA",
    "SIGNAL_RUN_V2_SCHEMA",
    "ConfirmationState",
    "CANONICAL_SIGNAL_MODEL_ID",
    "CANONICAL_SIGNAL_MODEL_VERSION",
    "CANONICAL_SIGNAL_TARGET_ID",
    "CandidateFeatureView",
    "CandidateFeatureViewV2",
    "CanonicalSignalModelV2",
    "CanonicalSignalSnapshotV3",
    "SignalFamily",
    "SignalFactorMapping",
    "SignalFactorMappingV2",
    "SignalFactorFreshnessPolicy",
    "SignalFactorName",
    "SignalFactorObservation",
    "SignalInputAssembler",
    "SignalInputAssemblerV3",
    "SignalInputMappingConfiguration",
    "SignalInputMappingConfigurationV2",
    "SignalFactorRequirementMode",
    "SignalFactorRequirementPolicy",
    "SignalMeaning",
    "SignalModel",
    "SignalModelConfig",
    "SignalModelRequest",
    "SignalModelResult",
    "SignalObservation",
    "SignalObservationV2",
    "SignalObservationV3",
    "SignalRunArtifact",
    "SignalRunArtifactV2",
    "SignalRunArtifactV3",
    "SignalModelConfigurationV2",
    "SignalSnapshot",
    "SignalState",
    "VerifiedSignalRunArtifactV2",
    "VerifiedSignalRunArtifactV3",
    "SIGNAL_RUN_V3_SCHEMA",
    "canonical_all_factors_required_policy",
    "canonical_signal_input_mapping",
    "canonical_signal_input_mapping_v2",
    "canonical_signal_freshness_policy",
    "canonical_signal_model_configuration_v2",
    "canonical_signal_model_definition",
    "persist_canonical_signal_model_for_research",
    "load_candidate_feature_view",
    "load_candidate_feature_view_v2",
    "load_verified_signal_run",
    "load_verified_signal_run_v2",
    "load_verified_signal_run_v3",
    "publish_candidate_feature_view",
    "publish_candidate_feature_view_v2",
    "publish_signal_run",
    "publish_signal_run_v2",
    "publish_signal_run_v3",
    "replay_signal_run",
    "replay_signal_run_v2",
    "replay_signal_run_v3",
    "register_canonical_signal_model_for_research",
    "run_signal_model",
    "run_signal_model_v2",
    "run_signal_model_v3",
]
