"""Deterministic stateful research contracts for WP-STATE-01."""

from market_regime_alpha.research.state_system.capital import (
    CapitalObservation,
    CapitalState,
    CapitalStateEvaluation,
    CapitalTransition,
    StatefulCapitalState,
    evaluate_capital_state,
)
from market_regime_alpha.research.state_system.common import StateLineage
from market_regime_alpha.research.state_system.configuration import (
    CapitalStateConfiguration,
    DynamicPoolConfiguration,
    EtfRotationConfiguration,
    MarketStateConfiguration,
    MissingDataPolicy,
    ThemeRotationConfiguration,
    TransitionThresholds,
)
from market_regime_alpha.research.state_system.market import (
    MarketRegimeObservation,
    MarketRegimeState,
    MarketRegimeTransition,
    MarketStateEvaluation,
    StatefulMarketRegime,
    evaluate_market_state,
)
from market_regime_alpha.research.state_system.etf_rotation import (
    EtfRotationEvaluation,
    EtfRotationObservation,
    EtfRotationState,
    EtfRotationTransition,
    StatefulEtfRotation,
    evaluate_etf_rotation,
)
from market_regime_alpha.research.state_system.theme_rotation import (
    StatefulThemeRotation,
    ThemeRotationEvaluation,
    ThemeRotationObservation,
    ThemeRotationState,
    ThemeRotationTransition,
    evaluate_theme_rotation,
)
from market_regime_alpha.research.state_system.pool import (
    DynamicPoolEvaluation,
    DynamicPoolEvaluationStatus,
    DynamicPoolStateContext,
    DynamicStockPoolVersion,
    PoolEligibilityObservation,
    evaluate_dynamic_pool,
)
from market_regime_alpha.research.state_system.research_integration import (
    EmpiricalForecastBias,
    EmpiricalForecastStatus,
    FeatureExposureAudit,
    SignalV4State,
    StateBoundCandidateSet,
    StateBoundEmpiricalForecastV2,
    StateBoundSignalV4,
    audit_feature_exposures,
    bind_candidate_set,
    project_empirical_forecast_v2,
    project_signal_v4,
)

__all__ = [
    "CapitalStateConfiguration",
    "CapitalObservation",
    "CapitalState",
    "CapitalStateEvaluation",
    "CapitalTransition",
    "EtfRotationConfiguration",
    "DynamicPoolConfiguration",
    "DynamicPoolEvaluation",
    "DynamicPoolEvaluationStatus",
    "DynamicPoolStateContext",
    "DynamicStockPoolVersion",
    "EtfRotationEvaluation",
    "EtfRotationObservation",
    "EtfRotationState",
    "EtfRotationTransition",
    "EmpiricalForecastBias",
    "EmpiricalForecastStatus",
    "FeatureExposureAudit",
    "MarketStateConfiguration",
    "MarketRegimeObservation",
    "MarketRegimeState",
    "MarketRegimeTransition",
    "MarketStateEvaluation",
    "MissingDataPolicy",
    "PoolEligibilityObservation",
    "SignalV4State",
    "StateLineage",
    "StatefulMarketRegime",
    "StateBoundCandidateSet",
    "StateBoundEmpiricalForecastV2",
    "StateBoundSignalV4",
    "StatefulEtfRotation",
    "StatefulCapitalState",
    "StatefulThemeRotation",
    "ThemeRotationConfiguration",
    "ThemeRotationEvaluation",
    "ThemeRotationObservation",
    "ThemeRotationState",
    "ThemeRotationTransition",
    "TransitionThresholds",
    "evaluate_market_state",
    "evaluate_etf_rotation",
    "evaluate_capital_state",
    "evaluate_dynamic_pool",
    "evaluate_theme_rotation",
    "audit_feature_exposures",
    "bind_candidate_set",
    "project_empirical_forecast_v2",
    "project_signal_v4",
]
