"""Closed Market/PIT vocabularies."""

from enum import StrEnum


class PriceBasis(StrEnum):
    RAW_UNADJUSTED = "RAW_UNADJUSTED"
    FORWARD_ADJUSTED = "FORWARD_ADJUSTED"
    BACKWARD_ADJUSTED = "BACKWARD_ADJUSTED"


class ProviderKind(StrEnum):
    PUBLIC_ENDPOINT = "PUBLIC_ENDPOINT"
    DATA_VENDOR = "DATA_VENDOR"
    BROKER_FEED = "BROKER_FEED"


class InstrumentType(StrEnum):
    EQUITY = "EQUITY"
    ETF = "ETF"
    INDEX = "INDEX"
    FUND = "FUND"
    BOND = "BOND"


class MembershipStatus(StrEnum):
    MEMBER = "MEMBER"
    NOT_MEMBER = "NOT_MEMBER"


class ClassificationEvidenceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    MISSING = "MISSING"


class EvidenceScope(StrEnum):
    DECISION_SESSION = "DECISION_SESSION"
    PRIOR_SESSION = "PRIOR_SESSION"
    EFFECTIVE_INTERVAL = "EFFECTIVE_INTERVAL"


class CorporateActionType(StrEnum):
    CASH_DIVIDEND = "CASH_DIVIDEND"
    STOCK_DIVIDEND = "STOCK_DIVIDEND"
    SPLIT = "SPLIT"
    RIGHTS_ISSUE = "RIGHTS_ISSUE"
    CONVERSION = "CONVERSION"
    MERGER = "MERGER"


class MarketFactKind(StrEnum):
    INSTRUMENT = "INSTRUMENT"
    INSTRUMENT_IDENTIFIER = "INSTRUMENT_IDENTIFIER"
    TRADING_SESSION = "TRADING_SESSION"
    CLASSIFICATION = "CLASSIFICATION"
    CLASSIFICATION_MEMBERSHIP = "CLASSIFICATION_MEMBERSHIP"
    MARKET_BAR = "MARKET_BAR"
    INSTRUMENT_FACT = "INSTRUMENT_FACT"
    CORPORATE_ACTION = "CORPORATE_ACTION"


class InstrumentFactKind(StrEnum):
    SECURITY_STATUS = "SECURITY_STATUS"
    LISTING_STATUS = "LISTING_STATUS"
    SPECIAL_TREATMENT_STATUS = "SPECIAL_TREATMENT_STATUS"
    TOTAL_SHARES = "TOTAL_SHARES"
    FREE_FLOAT_SHARES = "FREE_FLOAT_SHARES"
    LIMIT_UP_PRICE = "LIMIT_UP_PRICE"
    LIMIT_DOWN_PRICE = "LIMIT_DOWN_PRICE"
    REFERENCE_PRICE = "REFERENCE_PRICE"


class NumericInstrumentFactKind(StrEnum):
    TOTAL_SHARES = "TOTAL_SHARES"
    FREE_FLOAT_SHARES = "FREE_FLOAT_SHARES"
    LIMIT_UP_PRICE = "LIMIT_UP_PRICE"
    LIMIT_DOWN_PRICE = "LIMIT_DOWN_PRICE"
    REFERENCE_PRICE = "REFERENCE_PRICE"


class GapFactKind(StrEnum):
    DATA_CAPTURE = "DATA_CAPTURE"
    INSTRUMENT = "INSTRUMENT"
    INSTRUMENT_IDENTIFIER = "INSTRUMENT_IDENTIFIER"
    TRADING_SESSION = "TRADING_SESSION"
    CLASSIFICATION = "CLASSIFICATION"
    CLASSIFICATION_MEMBERSHIP = "CLASSIFICATION_MEMBERSHIP"
    MARKET_BAR = "MARKET_BAR"
    INSTRUMENT_FACT = "INSTRUMENT_FACT"
    CORPORATE_ACTION = "CORPORATE_ACTION"


class GapReasonCode(StrEnum):
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    NO_ROWS_RETURNED = "NO_ROWS_RETURNED"
    EXPECTED_OBSERVATION_MISSING = "EXPECTED_OBSERVATION_MISSING"
    EXACT_BAR_MISSING = "EXACT_BAR_MISSING"
    NULL_OHLC_PLACEHOLDER = "NULL_OHLC_PLACEHOLDER"
    CONFLICTING_SOURCE_REVISIONS = "CONFLICTING_SOURCE_REVISIONS"
    INVALID_OHLC = "INVALID_OHLC"


class BarTimeframe(StrEnum):
    MINUTE_1 = "MINUTE_1"
    MINUTE_5 = "MINUTE_5"
    MINUTE_15 = "MINUTE_15"
    MINUTE_30 = "MINUTE_30"
    MINUTE_60 = "MINUTE_60"
    DAILY = "DAILY"


class CaptureStatus(StrEnum):
    CAPTURED = "CAPTURED"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"


class SourceAvailabilityStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    PROVIDER_REPORTED = "PROVIDER_REPORTED"


class GapKind(StrEnum):
    MISSING = "MISSING"
    PLACEHOLDER = "PLACEHOLDER"
    PROVIDER_FAILURE = "PROVIDER_FAILURE"
    CONFLICT = "CONFLICT"
    INVALID_OHLC = "INVALID_OHLC"


class SecurityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    UNKNOWN = "UNKNOWN"


class ListingStatus(StrEnum):
    PRE_LISTING = "PRE_LISTING"
    LISTED = "LISTED"
    DELISTED = "DELISTED"
    UNKNOWN = "UNKNOWN"


class SpecialTreatmentStatus(StrEnum):
    NORMAL = "NORMAL"
    ST = "ST"
    STAR_ST = "STAR_ST"
    UNKNOWN = "UNKNOWN"
